name: Build devtools packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [lynx-ubuntu-22.04-avd-large]
        node-version: [18.20.2]
        pnpm-version: [7.33.6]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install

      - name: Fetch depot_tools
        run: |
          pnpm run fetch:depot_tools
          echo "fetch:depot_tools done"

      - name: Sync devtools-gn
        run: |
          export PATH=$(pwd)/packages/devtools-frontend-lynx/buildtools/depot_tools:$PATH
          pnpm run sync:devtools-gn
          echo "sync:devtools-gn done"
      
      - name: Build devtools-gn
        run: |
          pnpm run build:devtools
          echo "build:devtools done"

      - name: Sync devtools-dist
        run: |
          pnpm run sync:devtools-dist
          echo "sync:devtools-dist done"

      - name: Build all packages
        run: |
          pnpm run build:all
          echo "build:all done"