name: DevTools Web Simulator CI

on:
  pull_request:
    paths:
      - 'packages/devtools-web-simulator/**'
      - '.github/workflows/devtools-web-simulator-ci.yml'
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Build @lynx-js/devtools-web-simulator
    runs-on: lynx-ubuntu-22.04-avd-large
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (package scope)
        working-directory: packages/devtools-web-simulator
        run: |
          npm install

      - name: Type-check
        working-directory: packages/devtools-web-simulator
        run: npx tsc -b

      - name: Build (Rsbuild)
        working-directory: packages/devtools-web-simulator
        run: npm run build


