name: Deploy GitHub Pages (Frontend + Simulator)

on:
  push:
    branches: ["main"]
    paths:
      - 'packages/devtools-frontend-lynx/**'
      - 'packages/devtools-web-simulator/**'
      - '.github/workflows/gh-deploy.yml'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: lynx-ubuntu-22.04-medium
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack (use pnpm from packageManager)
        run: corepack enable

      - name: Install dependencies (root)
        run: pnpm install

      - name: Ensure python (user bin)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.local/bin"
          PY3=$(which python3)
          ln -sf "$PY3" "$HOME/.local/bin/python"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          python --version

      # Build DevTools Frontend (lynx)
      - name: Build DevTools Frontend (lynx)
        run: pnpm run build:devtools-frontend-lynx

      - name: Locate DevTools Frontend artifacts
        id: locate_frontend
        shell: bash
        run: |
          set -euo pipefail
          FRONT_DIR=$(ls -d packages/devtools-frontend-lynx/output/front_end_* | tail -n 1)
          TAR_FILE=$(ls -1 packages/devtools-frontend-lynx/output/devtool.frontend.lynx_*.tar.gz | tail -n 1)
          echo "FRONT_DIR=$FRONT_DIR" >> $GITHUB_ENV
          echo "TAR_FILE=$TAR_FILE" >> $GITHUB_ENV
          echo "Front dir: $FRONT_DIR"
          echo "Tarball: $TAR_FILE"

      # Build DevTools Web Simulator (rsbuild)
      - name: Install deps (simulator)
        working-directory: packages/devtools-web-simulator
        run: npm install

      - name: Build Simulator
        working-directory: packages/devtools-web-simulator
        env:
          ASSET_PREFIX: /${{ github.event.repository.name }}/devtools-web-simulator/
        run: npm run build

      - name: Prepare Pages content
        shell: bash
        run: |
          set -euo pipefail
          # simulator
          mkdir -p pages-out/devtools-web-simulator
          cp -r packages/devtools-web-simulator/dist/* pages-out/devtools-web-simulator/
          # frontend
          mkdir -p pages-out/devtools-frontend-lynx
          cp -r "$FRONT_DIR"/* pages-out/devtools-frontend-lynx/
          cp "$FRONT_DIR/devtools_app.html" pages-out/devtools-frontend-lynx/index.html
          # root index
          cat > pages-out/index.html <<'EOF'
          <!doctype html>
          <html>
            <head>
              <meta charset="utf-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <title>Lynx Devtools</title>
            </head>
            <body>
              <h1>Lynx Devtools</h1>
              <p><a href="/${{ github.event.repository.name }}/devtools-frontend-lynx/">Open DevTools Frontend (lynx)</a></p>
              <p><a href="/${{ github.event.repository.name }}/devtools-web-simulator/">Open DevTools Web Simulator</a></p>
            </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages-out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Create GitHub Release and upload tarball
        uses: softprops/action-gh-release@v2
        with:
          tag_name: devtools-frontend-lynx-${{ github.run_number }}
          name: DevTools Frontend (lynx) build #${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            ${{ env.TAR_FILE }}


